import { Project } from "@/types/Project";

export const projects: Project[] = [
  {
    image: "/khana.png",
    title: "Khana AI",
    content:
      "AN AI powered recipe generator which helps you generate recipes based on the ingredients you have at home. Just enter the ingredients and the AI will generate a recipe for you!",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: [
      "react",
      "Supabase",
      "Open AI",
      "Shadcn",
      "tailwind CSS",
    ],
    github: "https://github.com/Hydra016/Khana-Ai",
    deployed: "https://khana-xi.vercel.app/",
  },
  {
    image: "/tweaklify.png",
    title: "Tweaklify",
    content:
      "Tweaklify is a chrome extension which makes dev tools easier to use. It helps you to tweak the css of any website and see the changes in real time without changing the css from devtools, just use simple inputs and tweak the css of any website!",
    type: "web",
    subtype: "react",
    size: "small",
    techStack: ["React", "Chrome Extension"],
    github: "https://github.com/Hydra016/Tweaklify",
    deployed: "https://tweaklify.vercel.app/",
  },
  {
    image: "/clipster.png",
    title: "Clipster",
    content:
      "AI powered study assistant which generate questions based on the user specific study materials. just upload the text or you pdf book and the AI will generate questions for you to answer!",
    type: "web",
    subtype: "react",
    size: "small",
    techStack: ["nextJS", "typescript", "bun", "openAI"],
    github: "https://github.com/Zav141DJacob/hack4ai-clipster",
    deployed: "https://hack4ai-clipster.vercel.app/intro",
  },
  {
    image: "/visualizeit.png",
    title: "Visualize It",
    content:
      "A lightweight version of canva which helps you create amazing graphics and posters. Visualize it is a great tool for designers and non-designers alike. It has a lot of features like drag and drop, object creation, text editing, etc.",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: [
      "react",
      "fabric js",
      "Shadcn",
      "tailwind CSS",
    ],
    github: "https://github.com/Hydra016/Visualizeit",
    deployed: "https://visualizeit-ten.vercel.app/",
  },
  {
    image: "/ifctroll.png",
    title: "IFC Troll",
    content:
      "A web app that was built in 48 hours for a hackathon, it helps converrting ifc files to real 3d models and then detects the connections in the model and identifies different connections.",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: [
      "react",
      "web ifc viewer",
      "Shadcn",
      "tailwind CSS",
      "python"
    ],
    github: "https://github.com/Zav141DJacob/ifc-troll",
    deployed: "https://ifctroll.vercel.app/",
  },
  {
    image: "/pathLabs.png",
    title: "Path Labs",
    content:
      "Built with tensorflow!, enough for you to think there is machine learning involved. Pathlabs helps patients to check the percentage they are proned to heart attack. It has amazing UI and a great potential to be something big.",
    type: "web",
    subtype: "react",
    size: "small",
    techStack: ["Next JS", "tensorflow JS"],
    github: "https://github.com/Hydra016/Path-Labs",
    deployed: "https://path-labs.vercel.app/",
  },
  {
    image: "/Edurio.png",
    title: "Edurio",
    content:
      "Edurio helps users to create custom forms easily!, In the initial release the users are limited to create a single form with 2 types of questions i.e. multiple choice and open text.",
    type: "web",
    subtype: "vue",
    size: "small",
    techStack: ["Vue", "typescript"],
    github: "https://github.com/Hydra016/Edurio-task",
    deployed: "https://edurio-task.vercel.app/#/",
  },
  {
    image: "/manemp.png",
    title: "Manemp",
    content:
      "An app which helps the retail business to manange the business properly, from time tracking to managin inventory, Manemp does it all!",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: [
      "react",
      "node JS",
      "mongoDB",
      "websockets",
      "expressJS",
      "tailwind CSS",
    ],
    github: "https://github.com/Hydra016/Manemp-Client",
  },
  {
    image: "/Physio.png",
    title: "Physio AI",
    content:
      "A perfect spotter for your physiotherapy. It helps you to do exercise better and improves your form by giving realtime feedback!",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: ["react", "tensorflow JS", "neumorphism CSS"],
    github: "https://github.com/Hydra016/AI-Physiotherapist",
    deployed: "https://ai-physiotherapist.vercel.app/",
  },
  {
    image: "/urbanAbode.png",
    title: "Urban Abode",
    content:
      "A perfect website to help users search for properties across california, multiple filters to find the most suitable property along with an amazing price prediction module which helps you predict the price based on specific parameters.",
    type: "web",
    subtype: "react",
    size: "small",
    techStack: ["Next JS", "tensorflow JS"],
    github: "https://github.com/Hydra016/urbanAbode",
    deployed: "https://urban-abode-yfz1.vercel.app/",
  },
  {
    image: "/VetrinaLive.png",
    title: "Vetrina Live",
    content: "Clone of a leading ecommerce website in Italy.",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: ["react", "material UI"],
    github: "https://github.com/Hydra016/Vetrina-Live",
    deployed: "https://hydra016.github.io/Vetrina-Live/",
  },
  {
    image: "/talkative.png",
    title: "Talk A Tive",
    content:
      "Bored of same old boring chat apps? Try talkative! A cool chat app which helps users to chat in realtime with end to end encrypted chats so nobody can see you messages!.",
    type: "web",
    subtype: "react",
    size: "small",
    techStack: [
      "react",
      "node JS",
      "websockets",
      "chakra UI",
      "express",
      "mongoDB",
    ],
    github: "https://github.com/Hydra016/Talk-A-Tive",
  },
  {
    image: "/VocabeVoyage.png",
    title: "Vocab Voyage",
    content:
      "Looking for a new way of learning French? Well, no problem! Vocab Voyage is here!. Vocab Voyage is a perfect web app which helps you learn French by gamifying the experience and even goes one step further by making it multiplayer!.",
    type: "web",
    subtype: "react",
    size: "small",
    techStack: ["next JS", "mongoDB", "chakra UI", "websockets"],
    github: "https://github.com/Hydra016/Vocab-Voyage",
    deployed: "https://vocab-voyage.vercel.app/",
  },
  {
    image: "/ImperiaOrganic.png",
    title: "Imperia Organic Admin",
    content:
      "Every good app requires a great admin. Imperia Organic is a great tool made just for the Imperia Organic mobile app, The customer loved it!",
    type: "web",
    subtype: "react",
    size: "large",
    techStack: ["react", "mongoDB", "node JS", "material UI", "expressJS"],
    github: "https://github.com/Hydra016/Admin-Imperia-Frontend",
  },

  {
    image: "/houseApp.png",
    title: "DTT Properties",
    content:
      "Looking for properties around Amsterdam? Well not worries now! DTT Properties is all you need to make your search swift and easy. With multiple filters you can sell or rent a property anywhere around Amsterdam EASILY!.",
    type: "web",
    subtype: "vue",
    size: "large",
    techStack: ["vue"],
    github: "https://github.com/Hydra016/house-app",
  },
  {
    image: "/dispo.png",
    title: "Dispo Clone",
    content: "Clone of a leading car rental company in Latvia.",
    type: "web",
    subtype: "vue",
    size: "small",
    techStack: ["vue"],
    github: "https://github.com/Hydra016/Dispo-Task",
    deployed: "https://stalwart-yeot-61d4c6.netlify.app/",
  },
  {
    image: "/AmazeMe.png",
    title: "Amaze Me",
    content:
      "Tired of all the laggy ecommerce stores with a ton of unnecessary ads? Try Amaze ME! It will surely amaze you, with a large variety of fashion accessories, Amaze me will amaze you with it's immersive UI and swift shopping experience!",
    type: "web",
    subtype: "svelte",
    size: "small",
    techStack: ["Svelte"],
    github: "https://amaze-me-gamma.vercel.app/",
    deployed: "https://github.com/Hydra016/AmazeMe",
  },
  {
    image: "/worldofmovies.png",
    title: "World Of Movies",
    content:
      "All the movies along with their reviews available at a single place. World of Movies will definitely make oyur never ending search for the best movie a little easier.",
    type: "web",
    subtype: "svelte",
    size: "large",
    techStack: ["Svelte"],
    github: "https://github.com/Hydra016/world-of-movies",
  },

  {
    image: "/ImperiaOrganicMobile.png",
    title: "Imperia Organic App",
    content:
      "An app for a company based in Latvia called Imperia Organic. They sell fresh Japanese mushrooms in Riga. The app is equiped with augmented reality taking the user experience to the next level!",
    type: "mobile",
    size: "small",
    techStack: ["react native", "node JS", "expressJS", "native base"],
    github: "https://github.com/Devleed/mushroom-app",
  },
  {
    image: "/SmartDriver.png",
    title: "Smart Driver",
    content:
      "A perfect app to help reduce rash driving. Smart driver tracks your driving via the accelerometer in your phone and creates an analysis, that analysis is provided to the insurance companies who decide what you next insurance plan should be!",
    type: "mobile",
    size: "large",
    techStack: ["react native", "digital ocean", "django", "native base"],
    github: "https://github.com/Hydra016/smart-driver",
  },
  {
    image: "/Electrogram.png",
    title: "Electrogram",
    content:
      "Can't find the best phone? or headphones? or any electronics accessory? then Electrogram is your go to place. Electrogram has a variety of products for users to search for their perfect product!.",
    type: "mobile",
    size: "small",
    techStack: ["react native", "firebase", "native base"],
    github: "https://github.com/Hydra016/Software-Engineering-Project",
  },
  {
    image: "/Spencer.png",
    title: "Spencer",
    content:
      "A Blog website which helps you create, read, update and delete your blogs!",
    type: "web",
    subtype: "vue",
    size: "large",
    techStack: ["Vue", "typescript", "vue-material"],
    github: "https://github.com/Hydra016/Spencer",
    deployed: "https://spencer-steel.vercel.app/",
  },
];
